# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5b6a2feef4797cd6fdb09a1f88f6a1435f24b258280bdfc867e3f071b77998d1b0fdb358f7a744ead936fb05ee35424cb763190788ba502da65c68b43796f5

test:
  secret_key_base: 3743ba4f4c46b2e5d16f42351fab819ec97240f8b7f3a48283651b5b7be99c496f93ed9cae91c80dcba49b48fdd0e19918ea3830c0b8a096b7c5e83525005379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
